# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  debug:
    desc: Run the application in debug mode
    cmds:
      - pnpm dev

  release:
    aliases:
      - dist
    desc: Build and package the application for release
    cmds:
      - pnpm release
      - git add -f dist/*